### LEGACY/DEPRECATED FILE
### This Dockerfile was retained in `deployment/legacy` as an archival copy.
### The project is configured to deploy via SSH artifacts instead of Docker images.
### This file is intentionally left blank and will be removed upon request.
